import { useMemo } from "react";
import { jsPDF } from "jspdf";
import { Link } from "@tanstack/react-router";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Download, FileSpreadsheet, Copy, Archive, ShieldCheck, Bot, Workflow, TriangleAlert as AlertTriangle, CircleCheck as CheckCircle2, Clock, FileText, ClipboardCheck, ArrowRight } from "lucide-react";
import { motion } from "motion/react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { countryNames } from "@/lib/company-context";
import type { ReportRow } from "@/routes/app.reports";

type Props = {
  report: ReportRow | null;
  open: boolean;
  onOpenChange: (v: boolean) => void;
  onArchive?: (r: ReportRow) => void;
};

function buildSummary(r: ReportRow) {
  const findings = mockFindings(r);
  const lines = [
    `PayClarity — ${r.name}`,
    `Cycle: ${r.cycle}  •  Status: ${r.status}  •  Created: ${r.date}`,
    `Countries covered: ${countryNames(r.countries).join(", ")}`,
    `Employees analysed: ${r.employees.toLocaleString()}  •  Risk: ${r.risk}  •  Readiness: ${r.readiness}%`,
    "",
    "Executive summary",
    `This ${r.cycle} assessment covers ${r.employees.toLocaleString()} employees across ${r.countries.length} country/countries. Overall readiness for the EU Pay Transparency Directive is ${r.readiness}% with ${r.risk.toLowerCase()} residual risk. ${findings.length} finding(s) require attention before submission.`,
    "",
    "Country breakdown",
    ...r.countries.map(
      (c) =>
        `  • ${countryNames([c])[0]} — ${Math.round(
          r.employees / r.countries.length
        ).toLocaleString()} employees, readiness ${Math.max(
          40,
          r.readiness - r.countries.indexOf(c) * 6
        )}%`
    ),
    "",
    "Key findings",
    ...findings.map((f) => `  • [${f.severity}] ${f.title} — ${f.detail}`),
    "",
    "Generated by PayClarity  •  payclarity.app",
  ];
  return lines.join("\n");
}

function mockFindings(r: ReportRow) {
  return [
    {
      severity: r.risk === "High" ? "High" : "Medium",
      title: "Unexplained gap in Sales cluster",
      detail: "Adjusted pay gap of 6.4% for female employees at band B3 in Germany exceeds the 5% threshold.",
      ai: "AI compared 42 employees across 3 role clusters. Tenure and performance explain 3.1 pts; 3.3 pts remain unexplained and require a documented justification.",
    },
    {
      severity: "Medium",
      title: "4 employees ungrouped",
      detail: "Ungrouped employees are excluded from statutory ratios and must be resolved before submission.",
      ai: "AI could not confidently assign roles to standard comparators — job titles use custom internal codes.",
    },
    {
      severity: "Low",
      title: "Snapshot date differs from statutory reference date",
      detail: "Payroll snapshot is dated Mar 2026, statutory reference is Dec 2025.",
      ai: "AI flagged this for legal review. Recommend re-uploading a Dec 2025 snapshot or documenting the deviation.",
    },
  ] as const;
}

const WORKFLOW = [
  { key: "upload", label: "Data uploaded", icon: FileText },
  { key: "validate", label: "AI validation", icon: Bot },
  { key: "human", label: "Human review", icon: Workflow },
  { key: "submit", label: "Submitted", icon: CheckCircle2 },
] as const;

function currentStage(status: ReportRow["status"]) {
  return status === "Draft" || status === "Data upload"
    ? 1
    : status === "In review"
      ? 2
      : 3;
}

export function ReportDetailsDrawer({ report, open, onOpenChange, onArchive }: Props) {
  const findings = useMemo(() => (report ? mockFindings(report) : []), [report]);
  if (!report) return null;
  const stage = currentStage(report.status);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildSummary(report));
      toast.success("Report summary copied to clipboard.");
    } catch {
      toast.error("Could not copy to clipboard.");
    }
  };

  const handleDownloadPdf = () => {
  console.log("PDF button clicked");

  try {
    const doc = new jsPDF();

    console.log("jsPDF created");

    doc.text("Hello PayClarity!", 20, 20);

    console.log("Text added");

    doc.save("test.pdf");

    console.log("PDF saved");
  } catch (err) {
    console.error(err);
  }
};

  const handleExportCsv = () => {
    const rows = [
      ["Country", "Employees", "Readiness", "Risk"],
      ...report.countries.map((c) => [
        countryNames([c])[0],
        String(Math.round(report.employees / report.countries.length)),
        `${Math.max(
          40,
          report.readiness - report.countries.indexOf(c) * 6
        )}%`,
        report.risk,
      ]),
    ];

    const csv = rows
      .map((row) => row.map(csvEscape).join(","))
      .join("\n");

    triggerDownload(
      new Blob([csv], { type: "text/csv" }),
      `${slug(report.name)}.csv`
    );

    toast.success("CSV export ready");
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full overflow-y-auto p-0 sm:max-w-2xl">
        <div className="sticky top-0 z-10 border-b border-border/60 bg-card/95 px-6 py-5 backdrop-blur">
          <SheetHeader className="space-y-1 text-left">
            <div className="flex items-center gap-2 text-[11px] uppercase tracking-widest text-muted-foreground">
              <ShieldCheck className="h-3.5 w-3.5 text-teal" /> {report.cycle} assessment
            </div>
            <SheetTitle className="font-display text-xl">{report.name}</SheetTitle>
            <SheetDescription>
              {countryNames(report.countries).join(" · ")} · {report.employees.toLocaleString()} employees
            </SheetDescription>
          </SheetHeader>
          <div className="mt-4 flex flex-wrap gap-2">
            <Button size="sm" variant="hero" onClick={handleDownloadPdf}>
              <Download className="mr-1 h-3.5 w-3.5" /> Download PDF
            </Button>
            <Button size="sm" variant="outline" onClick={handleExportCsv}>
              <FileSpreadsheet className="mr-1 h-3.5 w-3.5" /> Export CSV
            </Button>
            <Button size="sm" variant="outline" onClick={handleCopy}>
              <Copy className="mr-1 h-3.5 w-3.5" /> Copy summary
            </Button>
            <Button
              size="sm"
              variant="ghost"
              className="ml-auto text-destructive hover:text-destructive"
              onClick={() => onArchive?.(report)}
            >
              <Archive className="mr-1 h-3.5 w-3.5" /> Archive
            </Button>
          </div>
        </div>

        <div className="space-y-6 p-6">
          {/* Overview */}
          <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Stat label="Status" value={report.status} />
            <Stat label="Risk" value={report.risk} />
            <Stat label="Readiness" value={`${report.readiness}%`} />
            <Stat label="Created" value={report.date} />
          </section>

          {/* Workflow */}
          <section>
            <SectionTitle icon={Workflow}>Workflow progress</SectionTitle>
            <div className="mt-3 grid grid-cols-4 gap-2">
              {WORKFLOW.map((s, i) => {
                const done = i < stage;
                const active = i === stage;
                return (
                  <motion.div
                    key={s.key}
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className={cn(
                      "rounded-lg border p-3 text-center",
                      done
                        ? "border-success/40 bg-success/5 text-success"
                        : active
                          ? "border-teal/40 bg-teal/5 text-teal"
                          : "border-border/60 bg-background text-muted-foreground",
                    )}
                  >
                    <s.icon className="mx-auto h-4 w-4" />
                    <div className="mt-1 text-[11px] font-medium">{s.label}</div>
                  </motion.div>
                );
              })}
            </div>
          </section>

          {/* Executive summary */}
          <section>
            <SectionTitle icon={FileText}>Executive summary</SectionTitle>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              This {report.cycle} assessment covers{" "}
              <span className="font-medium text-foreground">
                {report.employees.toLocaleString()} employees
              </span>{" "}
              across {report.countries.length} country/countries. Overall readiness for the EU Pay
              Transparency Directive is{" "}
              <span className="font-medium text-foreground">{report.readiness}%</span> with{" "}
              <span className="font-medium text-foreground">{report.risk.toLowerCase()}</span>{" "}
              residual risk. {findings.length} finding(s) require attention before submission.
            </p>
          </section>

          {/* Country breakdown */}
          <section>
            <SectionTitle icon={ShieldCheck}>Countries covered</SectionTitle>
            <div className="mt-3 overflow-hidden rounded-xl border border-border/60">
              <table className="w-full text-sm">
                <thead className="bg-muted/30 text-left text-[11px] uppercase tracking-wider text-muted-foreground">
                  <tr>
                    <th className="px-3 py-2 font-medium">Country</th>
                    <th className="px-3 py-2 font-medium">Employees</th>
                    <th className="px-3 py-2 font-medium">Readiness</th>
                    <th className="px-3 py-2 font-medium">Signal</th>
                  </tr>
                </thead>
                <tbody>
                  {report.countries.map((c, i) => {
                    const readiness = Math.max(40, report.readiness - i * 6);
                    return (
                      <tr key={c} className="border-t border-border/60">
                        <td className="px-3 py-2">{countryNames([c])[0]}</td>
                        <td className="px-3 py-2 tabular-nums">
                          {Math.round(report.employees / report.countries.length).toLocaleString()}
                        </td>
                        <td className="px-3 py-2">
                          <div className="flex items-center gap-2">
                            <div className="h-1.5 w-20 rounded-full bg-muted">
                              <div
                                className={cn(
                                  "h-1.5 rounded-full",
                                  readiness >= 90
                                    ? "bg-success"
                                    : readiness >= 60
                                      ? "bg-warning"
                                      : "bg-destructive",
                                )}
                                style={{ width: `${readiness}%` }}
                              />
                            </div>
                            <span className="text-xs tabular-nums text-muted-foreground">
                              {readiness}%
                            </span>
                          </div>
                        </td>
                        <td className="px-3 py-2 text-muted-foreground">
                          {readiness >= 90 ? "On track" : readiness >= 60 ? "Needs review" : "At risk"}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>

          {/* Findings */}
          <section>
            <SectionTitle icon={AlertTriangle}>Risk findings &amp; AI explanations</SectionTitle>
            <ul className="mt-3 space-y-3">
              {findings.map((f) => (
                <li
                  key={f.title}
                  className="rounded-xl border border-border/60 bg-background p-4"
                >
                  <div className="flex items-center gap-2">
                    <span
                      className={cn(
                        "rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-widest",
                        f.severity === "High"
                          ? "bg-destructive/10 text-destructive"
                          : f.severity === "Medium"
                            ? "bg-warning/10 text-warning"
                            : "bg-info/10 text-info",
                      )}
                    >
                      {f.severity}
                    </span>
                    <div className="text-sm font-medium">{f.title}</div>
                  </div>
                  <p className="mt-1.5 text-xs text-muted-foreground">{f.detail}</p>
                  <div className="mt-2 flex items-start gap-2 rounded-lg border border-teal/30 bg-teal/5 p-2.5 text-xs">
                    <Bot className="mt-0.5 h-3.5 w-3.5 shrink-0 text-teal" />
                    <div>
                      <div className="font-medium text-teal">AI explanation</div>
                      <div className="text-muted-foreground">{f.ai}</div>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <SectionTitle icon={Clock}>Timeline</SectionTitle>
            <ol className="mt-3 space-y-2 border-l border-border/60 pl-4 text-sm">
              <li className="relative">
                <span className="absolute -left-[21px] top-1.5 h-2 w-2 rounded-full bg-teal" />
                Report created — {report.date}
              </li>
              <li className="relative text-muted-foreground">
                <span className="absolute -left-[21px] top-1.5 h-2 w-2 rounded-full bg-muted-foreground/40" />
                Data validated by AI
              </li>
              <li className="relative text-muted-foreground">
                <span className="absolute -left-[21px] top-1.5 h-2 w-2 rounded-full bg-muted-foreground/40" />
                Awaiting sign-off from Legal
              </li>
            </ol>
          </section>

          {/* Human Review access */}
          <section>
            <Link
              to="/app/human-review"
              className="group flex items-center justify-between rounded-xl border border-teal/30 bg-teal/5 p-3 transition-all hover:-translate-y-0.5 hover:border-teal/40"
            >
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <ClipboardCheck className="h-4 w-4 text-teal" />
                Review and approve explanations in Human Review
              </div>
              <ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-teal" />
            </Link>
          </section>
        </div>
      </SheetContent>
    </Sheet>
  );
}

function SectionTitle({ icon: Icon, children }: { icon: typeof FileText; children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground">
      <Icon className="h-3.5 w-3.5 text-teal" /> {children}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border/60 bg-background p-3">
      <div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
      <div className="mt-1 text-sm font-medium">{value}</div>
    </div>
  );
}

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function csvEscape(v: string) {
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}
function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
