/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppValidateRouteImport } from './routes/app.validate'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppHumanReviewRouteImport } from './routes/app.human-review'
import { Route as AppGroupingRouteImport } from './routes/app.grouping'
import { Route as AppGenerateReportRouteImport } from './routes/app.generate-report'
import { Route as AppGapAnalysisRouteImport } from './routes/app.gap-analysis'
import { Route as AppExplanationsRouteImport } from './routes/app.explanations'
import { Route as AppExecutiveRouteImport } from './routes/app.executive'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDataSourcesRouteImport } from './routes/app.data-sources'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAssessmentsRouteImport } from './routes/app.assessments'
import { Route as AppReportsSetupRouteImport } from './routes/app.reports.setup'
import { Route as AppComplianceCountryCodeRouteImport } from './routes/app.compliance.$countryCode'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppValidateRoute = AppValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHumanReviewRoute = AppHumanReviewRouteImport.update({
  id: '/human-review',
  path: '/human-review',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupingRoute = AppGroupingRouteImport.update({
  id: '/grouping',
  path: '/grouping',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateReportRoute = AppGenerateReportRouteImport.update({
  id: '/generate-report',
  path: '/generate-report',
  getParentRoute: () => AppRoute,
} as any)
const AppGapAnalysisRoute = AppGapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppExplanationsRoute = AppExplanationsRouteImport.update({
  id: '/explanations',
  path: '/explanations',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutiveRoute = AppExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSetupRoute = AppReportsSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppComplianceCountryCodeRoute =
  AppComplianceCountryCodeRouteImport.update({
    id: '/$countryCode',
    path: '/$countryCode',
    getParentRoute: () => AppComplianceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/executive': typeof AppExecutiveRoute
  '/app/explanations': typeof AppExplanationsRoute
  '/app/gap-analysis': typeof AppGapAnalysisRoute
  '/app/generate-report': typeof AppGenerateReportRoute
  '/app/grouping': typeof AppGroupingRoute
  '/app/human-review': typeof AppHumanReviewRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/validate': typeof AppValidateRoute
  '/app/': typeof AppIndexRoute
  '/app/compliance/$countryCode': typeof AppComplianceCountryCodeRoute
  '/app/reports/setup': typeof AppReportsSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/executive': typeof AppExecutiveRoute
  '/app/explanations': typeof AppExplanationsRoute
  '/app/gap-analysis': typeof AppGapAnalysisRoute
  '/app/generate-report': typeof AppGenerateReportRoute
  '/app/grouping': typeof AppGroupingRoute
  '/app/human-review': typeof AppHumanReviewRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/validate': typeof AppValidateRoute
  '/app': typeof AppIndexRoute
  '/app/compliance/$countryCode': typeof AppComplianceCountryCodeRoute
  '/app/reports/setup': typeof AppReportsSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/executive': typeof AppExecutiveRoute
  '/app/explanations': typeof AppExplanationsRoute
  '/app/gap-analysis': typeof AppGapAnalysisRoute
  '/app/generate-report': typeof AppGenerateReportRoute
  '/app/grouping': typeof AppGroupingRoute
  '/app/human-review': typeof AppHumanReviewRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/validate': typeof AppValidateRoute
  '/app/': typeof AppIndexRoute
  '/app/compliance/$countryCode': typeof AppComplianceCountryCodeRoute
  '/app/reports/setup': typeof AppReportsSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/coming-soon'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/assessments'
    | '/app/audit'
    | '/app/compliance'
    | '/app/copilot'
    | '/app/data-sources'
    | '/app/employees'
    | '/app/executive'
    | '/app/explanations'
    | '/app/gap-analysis'
    | '/app/generate-report'
    | '/app/grouping'
    | '/app/human-review'
    | '/app/reports'
    | '/app/review'
    | '/app/settings'
    | '/app/validate'
    | '/app/'
    | '/app/compliance/$countryCode'
    | '/app/reports/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/assessments'
    | '/app/audit'
    | '/app/compliance'
    | '/app/copilot'
    | '/app/data-sources'
    | '/app/employees'
    | '/app/executive'
    | '/app/explanations'
    | '/app/gap-analysis'
    | '/app/generate-report'
    | '/app/grouping'
    | '/app/human-review'
    | '/app/reports'
    | '/app/review'
    | '/app/settings'
    | '/app/validate'
    | '/app'
    | '/app/compliance/$countryCode'
    | '/app/reports/setup'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/coming-soon'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/assessments'
    | '/app/audit'
    | '/app/compliance'
    | '/app/copilot'
    | '/app/data-sources'
    | '/app/employees'
    | '/app/executive'
    | '/app/explanations'
    | '/app/gap-analysis'
    | '/app/generate-report'
    | '/app/grouping'
    | '/app/human-review'
    | '/app/reports'
    | '/app/review'
    | '/app/settings'
    | '/app/validate'
    | '/app/'
    | '/app/compliance/$countryCode'
    | '/app/reports/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/validate': {
      id: '/app/validate'
      path: '/validate'
      fullPath: '/app/validate'
      preLoaderRoute: typeof AppValidateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/human-review': {
      id: '/app/human-review'
      path: '/human-review'
      fullPath: '/app/human-review'
      preLoaderRoute: typeof AppHumanReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grouping': {
      id: '/app/grouping'
      path: '/grouping'
      fullPath: '/app/grouping'
      preLoaderRoute: typeof AppGroupingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generate-report': {
      id: '/app/generate-report'
      path: '/generate-report'
      fullPath: '/app/generate-report'
      preLoaderRoute: typeof AppGenerateReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gap-analysis': {
      id: '/app/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/app/gap-analysis'
      preLoaderRoute: typeof AppGapAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explanations': {
      id: '/app/explanations'
      path: '/explanations'
      fullPath: '/app/explanations'
      preLoaderRoute: typeof AppExplanationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/executive': {
      id: '/app/executive'
      path: '/executive'
      fullPath: '/app/executive'
      preLoaderRoute: typeof AppExecutiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-sources': {
      id: '/app/data-sources'
      path: '/data-sources'
      fullPath: '/app/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments': {
      id: '/app/assessments'
      path: '/assessments'
      fullPath: '/app/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/setup': {
      id: '/app/reports/setup'
      path: '/setup'
      fullPath: '/app/reports/setup'
      preLoaderRoute: typeof AppReportsSetupRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/compliance/$countryCode': {
      id: '/app/compliance/$countryCode'
      path: '/$countryCode'
      fullPath: '/app/compliance/$countryCode'
      preLoaderRoute: typeof AppComplianceCountryCodeRouteImport
      parentRoute: typeof AppComplianceRoute
    }
  }
}

interface AppComplianceRouteChildren {
  AppComplianceCountryCodeRoute: typeof AppComplianceCountryCodeRoute
}

const AppComplianceRouteChildren: AppComplianceRouteChildren = {
  AppComplianceCountryCodeRoute: AppComplianceCountryCodeRoute,
}

const AppComplianceRouteWithChildren = AppComplianceRoute._addFileChildren(
  AppComplianceRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsSetupRoute: typeof AppReportsSetupRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsSetupRoute: AppReportsSetupRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppComplianceRoute: typeof AppComplianceRouteWithChildren
  AppCopilotRoute: typeof AppCopilotRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExecutiveRoute: typeof AppExecutiveRoute
  AppExplanationsRoute: typeof AppExplanationsRoute
  AppGapAnalysisRoute: typeof AppGapAnalysisRoute
  AppGenerateReportRoute: typeof AppGenerateReportRoute
  AppGroupingRoute: typeof AppGroupingRoute
  AppHumanReviewRoute: typeof AppHumanReviewRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppValidateRoute: typeof AppValidateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppAuditRoute: AppAuditRoute,
  AppComplianceRoute: AppComplianceRouteWithChildren,
  AppCopilotRoute: AppCopilotRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExecutiveRoute: AppExecutiveRoute,
  AppExplanationsRoute: AppExplanationsRoute,
  AppGapAnalysisRoute: AppGapAnalysisRoute,
  AppGenerateReportRoute: AppGenerateReportRoute,
  AppGroupingRoute: AppGroupingRoute,
  AppHumanReviewRoute: AppHumanReviewRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppValidateRoute: AppValidateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
